### ISSUE TITLE
Epic 1: Create Homepage (Week 1)

### ISSUE THREAD

**Issue by feizza615** [feizza615/pluvio#1]
- [ ] Create Header
- [ ] Create Footer
- [ ] Create Login Pop up
- [ ] Create Sign Up Pop up
- [ ] Create Homepage body
