### ISSUE TITLE
Epic 0: Setup (Week 0)

### ISSUE THREAD

**Issue by feizza615** [feizza615/pluvio#5]
- [x] Database
- [x] Set up Repo, environment
- [x] Watched React Crash Course
- [x] Set up Github Project Board
- [x] Finalized Figma theme/ worked on CSS
- [x] Created project and requirements.txt
